### ISSUE TITLE
플레이어 물리 개선

### ISSUE THREAD

**Issue by Arkru1204** [Ostracon14/ProjectBB#11]
# Description
플레이어의 물리 기능을 추가 및 개선
   
# Todo
- [x] 중력 수정
- [x] 대시 수정
- [x] 이동 속도 수정
- [x] 점프 힘 수정
- [x] 테스트 점프 맵 구현
- [x] 발판 아래로 점프 구현
- [x] 발판 아래에서 통과 구현
   
# ETC
<details>
<summary>[완료]</summary>

* 대시 대각선 이동 때 십자 이동보다 빠름, 수정 필요[완료]

   ![화면 캡처 2023-07-24 175003](https://github.com/Ostracon14/ProjectBB/assets/35932023/71be6abc-0740-4886-8cae-40308f596473)

* 대시 8방향 중 위/아래 방향이 안됨.
isMove 일 때(방향키 조작이 있을 때) 작동하게 해놨는데, 이게 Move()에서 x 축만 받아와서 그런듯[완료]

* 발판 아래 점프 관련 기능 전체적인 작명 수정 필요
레이어/태그/함수/InputManager
사유 : CanJumpDown CanNotJumpDown JumpDownOn JumpDownOff 하다가 게슈탈트붕괴올거같음[완료]

* 레이어는 Pass Ground에서 레이캐스트로 Ground로 변경[완료]

* 아래 점프 시 Ground를 잠시 Pass Ground로 변경[완료]

* 현재의 코드는 오브젝트 맵 기준임. 타일팔레트로 변경시 isGround로 하면 버그 가능성 있음[해결]

</details>

* 대시 스택 Max값 지정, 총 스택/현재 스택 확인

* 대시 쿨타임/스택 조건 변수로 변경
