### ISSUE TITLE
기본 전투 구현

### ISSUE THREAD

**Issue by Arkru1204** [Ostracon14/ProjectBB#12]
# Description
플레이어가 공격과 피격을 할 수 있도록 구현
   
# Todo
- [ ] 플레이어 공격(평타)
- [x] 플레이어 피격
- [x] 임시 에너미 구현
- [x] 트랩 구현
- [ ] 탄막 파괴 혹은 반사
   
# ETC
공격은 대부분 애니메이션에서 처리 (콜라이더 온오프)
